/*
 * generated by Xtext
 */
package mars.rover;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RoverDSLRuntimeModule extends mars.rover.AbstractRoverDSLRuntimeModule {

}
