/*
 * generated by Xtext
 */
package mars.rover.serializer;

import com.google.inject.Inject;
import java.util.List;
import mars.rover.services.RoverDSLGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class RoverDSLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected RoverDSLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Robot_ConstantsKeyword_3_0_q;
	protected AbstractElementAlias match_Robot_VariablesKeyword_2_0_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (RoverDSLGrammarAccess) access;
		match_Robot_ConstantsKeyword_3_0_q = new TokenAlias(false, true, grammarAccess.getRobotAccess().getConstantsKeyword_3_0());
		match_Robot_VariablesKeyword_2_0_q = new TokenAlias(false, true, grammarAccess.getRobotAccess().getVariablesKeyword_2_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if(match_Robot_ConstantsKeyword_3_0_q.equals(syntax))
				emit_Robot_ConstantsKeyword_3_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Robot_VariablesKeyword_2_0_q.equals(syntax))
				emit_Robot_VariablesKeyword_2_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'Constants:'?
	 *
	 * This ambiguous syntax occurs at:
	 *     behaviorOrder+=BehaviorName 'Variables:'? (ambiguity) 'Stops when:' stopBehaviour=ValueExpression
	 *     globals+=Global (ambiguity) 'Stops when:' stopBehaviour=ValueExpression
	 */
	protected void emit_Robot_ConstantsKeyword_3_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'Variables:'?
	 *
	 * This ambiguous syntax occurs at:
	 *     behaviorOrder+=BehaviorName (ambiguity) 'Constants:' statics+=Static
	 *     behaviorOrder+=BehaviorName (ambiguity) 'Constants:'? 'Stops when:' stopBehaviour=ValueExpression
	 */
	protected void emit_Robot_VariablesKeyword_2_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
