/**
 * generated by Xtext
 */
package mars.rover.validation;

import mars.rover.validation.AbstractRoverDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RoverDSLValidator extends AbstractRoverDSLValidator {
}
