/*
 * generated by Xtext
 */
package mars.rover;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RoverDSLUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return mars.rover.ui.internal.RoverDSLActivator.getInstance().getInjector("mars.rover.RoverDSL");
	}
	
}
