/**
 * generated by Xtext
 */
package mars.rover.generator;

import com.google.common.base.Objects;
import mars.rover.generator.RobotGenerator;
import mars.rover.roverDSL.Robot;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class RoverDSLGenerator implements IGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess fsa) {
    TreeIterator<EObject> _allContents = resource.getAllContents();
    EObject _head = IteratorExtensions.<EObject>head(_allContents);
    final Robot root = ((Robot) _head);
    boolean _notEquals = (!Objects.equal(root, null));
    if (_notEquals) {
      CharSequence _java = RobotGenerator.toJava(root);
      fsa.generateFile("robot.java", _java);
    }
  }
}
