/*
 * generated by Xtext
 */
package mars.rover.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RoverDSLUiModule extends mars.rover.ui.AbstractRoverDSLUiModule {
	public RoverDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
